name: "Github Action: get hosts every month"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run scripts
      run: |
        if [ -z "${{secrets.DOMAINS}}" ]; 
        then
          echo 'do you add a secret that named DOMAINS?'
          python main.py 'github.global.ssl.fastly.net,github.com,gist.github.com,assets-cdn.github.com,raw.githubusercontent.com,gist.githubusercontent.com,cloud.githubusercontent.com,camo.githubusercontent.com,avatars.githubusercontent.com,avatars0.githubusercontent.com,avatars1.githubusercontent.com,avatars2.githubusercontent.com,avatars3.githubusercontent.com,avatars4.githubusercontent.com,avatars5.githubusercontent.com,avatars6.githubusercontent.com,avatars7.githubusercontent.com,avatars8.githubusercontent.com,avatars.githubusercontent.com,github.githubassets.com,user-images.githubusercontent.com,codeload.github.com,favicons.githubusercontent.com,marketplace-screenshots.githubusercontent.com,repository-images.githubusercontent.com,api.github.com'
        else
          echo 'run...'
          python main.py ${{secrets.DOMAINS}} hosts.txt

          python main.py 'github.global.ssl.fastly.net,github.com,gist.github.com,assets-cdn.github.com,raw.githubusercontent.com,gist.githubusercontent.com,cloud.githubusercontent.com,camo.githubusercontent.com,avatars.githubusercontent.com,avatars0.githubusercontent.com,avatars1.githubusercontent.com,avatars2.githubusercontent.com,avatars3.githubusercontent.com,avatars4.githubusercontent.com,avatars5.githubusercontent.com,avatars6.githubusercontent.com,avatars7.githubusercontent.com,avatars8.githubusercontent.com,avatars.githubusercontent.com,github.githubassets.com,user-images.githubusercontent.com,codeload.github.com,favicons.githubusercontent.com,marketplace-screenshots.githubusercontent.com,repository-images.githubusercontent.com,api.github.com' public.txt
        fi
      env:
        domain: ${{secrets.DOMAINS}}
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: "Github Actions job result : your hosts"
        # Literal body:
        # body: Build job of ${{github.repository}} completed successfully!
        # Read file contents as body:
        body: file://hosts.txt
        to: ${{secrets.MAIL_RECEIVER}}
        from: Github Action # <user@example.com>
        # Optional carbon copy recipients
        # cc: kyloren@example.com,leia@example.com
        # Optional blind carbon copy recipients
        # bcc: r2d2@example.com,hansolo@example.com
        # Optional content type (defaults to text/plain):
        content_type: text/html
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        # attachments: attachments.zip,git.diff,./dist/static/main.js

    - name: Commit files
      run: |
        git config --local user.email "hy.lobby@gmail.com"
        git config --local user.name "hosts(bot)"
        git add public.txt
        git commit -m "Github action: updated on $(date +%Y-%m-%d)" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
